export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FAILD_INGREDIENT = 'FAILD_INGREDIENT'

export const PURCHASE_SUCC = 'PURCAHSE_SUCC';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_FAIL = 'PURCHASE_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCC = 'FETCH_ORDER_SUCC';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCC = 'AUTH_SUCC';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'